import { NextResponse } from "next/server";
import { CreateDeviceSchema } from "@/lib/validations";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET(request: Request) {
    const session = await getServerSession(authOptions);

    if (!session) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const isAscendingOrder = searchParams.get("order") === "created_asc";

    const devices = await prisma.device.findMany({
        where: {
            userId: session.user.id,
        },
        include: {
            activePlaylist: {
                select: {
                    id: true,
                    name: true,
                },
            },
            schedule: {
                select: {
                    id: true,
                    name: true,
                },
            },
            playingPlaylist: {
                select: {
                    id: true,
                    name: true,
                },
            },
        },
        orderBy: {
            createdAt: isAscendingOrder ? "asc" : "desc",
        },
    });

    const mediaItems = await prisma.mediaItem.findMany({
        where: {
            userId: session.user.id,
        },
        select: {
            name: true,
            filename: true,
            type: true,
            url: true,
        },
        orderBy: {
            createdAt: "desc",
        },
    });

    const mediaByFilename = new Map<string, { type: string; url: string; name: string }>();
    const mediaByName = new Map<string, { type: string; url: string; name: string }>();
    for (const media of mediaItems) {
        const preview = { type: media.type, url: media.url, name: media.name };
        if (media.filename && !mediaByFilename.has(media.filename)) {
            mediaByFilename.set(media.filename, preview);
        }
        if (!mediaByName.has(media.name)) {
            mediaByName.set(media.name, preview);
        }
    }

    // Calculate dynamic status based on lastSeenAt
    const devicesWithStatus = devices.map(device => {
        let status = "offline";

        if (device.lastSeenAt) {
            const lastSeenTime = new Date(device.lastSeenAt).getTime();
            const now = Date.now();
            const fiveMinutesInMs = 5 * 60 * 1000;

            // Device is online if it checked in within the last 5 minutes
            if (now - lastSeenTime < fiveMinutesInMs) {
                status = "online";
            }
        }

        return {
            ...device,
            connectivityStatus: status,
            contentPreview: device.currentContentName
                ? mediaByFilename.get(device.currentContentName) ?? mediaByName.get(device.currentContentName) ?? null
                : null,
        };
    });

    return NextResponse.json(devicesWithStatus);
}

export async function POST(request: Request) {
    const session = await getServerSession(authOptions);

    if (!session) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const json = await request.json();

        const result = CreateDeviceSchema.safeParse(json);
        if (!result.success) {
            return NextResponse.json(
                { error: result.error.issues[0].message },
                { status: 400 }
            );
        }

        const { name } = result.data;

        const device = await prisma.device.create({
            data: {
                name,
                userId: session.user.id,
                // token is auto-generated by default(cuid())
            },
        });

        return NextResponse.json(device);
    } catch (error) {
        console.error("Create device error:", error);
        return NextResponse.json(
            { error: "Failed to create device" },
            { status: 500 }
        );
    }
}
