import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET(request: Request) {
    const session = await getServerSession(authOptions);

    if (!session) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const devices = await prisma.device.findMany({
        where: {
            userId: session.user.id,
        },
        include: {
            activePlaylist: {
                select: {
                    id: true,
                    name: true,
                },
            },
        },
        orderBy: {
            createdAt: "desc",
        },
    });

    return NextResponse.json(devices);
}

export async function POST(request: Request) {
    const session = await getServerSession(authOptions);

    if (!session) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    try {
        const json = await request.json();
        const { name } = json;

        if (!name || typeof name !== "string") {
            return NextResponse.json(
                { error: "Device name is required" },
                { status: 400 }
            );
        }

        const device = await prisma.device.create({
            data: {
                name,
                userId: session.user.id,
                // token is auto-generated by default(cuid())
            },
        });

        return NextResponse.json(device);
    } catch (error) {
        console.error("Create device error:", error);
        return NextResponse.json(
            { error: "Failed to create device" },
            { status: 500 }
        );
    }
}
